config/routes.rb
Folio4::Application.routes.draw do
  resources :companies

  resources :vacancies
  
  devise_for :users
  root "vacancies#index"
  get "vacancies/new"
  get "vacancies/show"
  get "vacancies/delete"
  get "vacancies/edit"

  

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :vacancies
  has_many :users, :through => :users_vacancies
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_and_belongs_to_many :vacancies
  has_many :companies, :through => :vacancies
  
  # For PaperClip
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  belongs_to :company
  # has_and_belongs_to_many :skills
  has_and_belongs_to_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :status, :tax_number, :email, :password, :contact_person_first_name, :contact_person_last_name, :contact_person_mobile_number, :contact_person_email, :website, :office_phone_number, :description, :mail_verified, :company_verified, :address, :logo_large, :logo_small, :permalink)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
  end

  def edit
  end

  def new
     @user = User.create( params[:user] )
  end
  
  def create
     @user = User.create( params[:user] )
  end

  def show
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @vacancies = Vacancy.all
  end

  def show
  end

  def new
    @vacancy = current_user.vacancies.build
  end

  def edit
  end

  def create
    @vacancy = current_user.vacancies.build(vacancy_params)

    if @vacancy.save
      redirect_to @vacancy, notice: 'Vacancy was successfully created.' 
    else
      render action: 'new'
     end
  end

  
  def update
    if @vacancy.update(vacancy_params)
      redirect_to @vacancy, notice: 'Vacancy was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @vacancy.destroy
    redirect_to vacancies_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacancy_params
      params.require(:vacancy).permit(:company_id, :position, :description, :location, :from_home, :salary, :show_salary, :interview_address, :ongiong)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :tax_number %><br>
    <%= f.number_field :tax_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :contact_person_first_name %><br>
    <%= f.text_field :contact_person_first_name %>
  </div>
  <div class="field">
    <%= f.label :contact_person_last_name %><br>
    <%= f.text_field :contact_person_last_name %>
  </div>
  <div class="field">
    <%= f.label :contact_person_mobile_number %><br>
    <%= f.text_field :contact_person_mobile_number %>
  </div>
  <div class="field">
    <%= f.label :contact_person_email %><br>
    <%= f.text_field :contact_person_email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :office_phone_number %><br>
    <%= f.text_field :office_phone_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :mail_verified %><br>
    <%= f.check_box :mail_verified %>
  </div>
  <div class="field">
    <%= f.label :company_verified %><br>
    <%= f.check_box :company_verified %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :logo_large %><br>
    <%= f.text_field :logo_large %>
  </div>
  <div class="field">
    <%= f.label :logo_small %><br>
    <%= f.text_field :logo_small %>
  </div>
  <div class="field">
    <%= f.label :permalink %><br>
    <%= f.text_field :permalink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Tax number</th>
      <th>Email</th>
      <th>Password</th>
      <th>Contact person first name</th>
      <th>Contact person last name</th>
      <th>Contact person mobile number</th>
      <th>Contact person email</th>
      <th>Website</th>
      <th>Office phone number</th>
      <th>Description</th>
      <th>Mail verified</th>
      <th>Company verified</th>
      <th>Address</th>
      <th>Logo large</th>
      <th>Logo small</th>
      <th>Permalink</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.status %></td>
        <td><%= company.tax_number %></td>
        <td><%= company.email %></td>
        <td><%= company.password %></td>
        <td><%= company.contact_person_first_name %></td>
        <td><%= company.contact_person_last_name %></td>
        <td><%= company.contact_person_mobile_number %></td>
        <td><%= company.contact_person_email %></td>
        <td><%= company.website %></td>
        <td><%= company.office_phone_number %></td>
        <td><%= company.description %></td>
        <td><%= company.mail_verified %></td>
        <td><%= company.company_verified %></td>
        <td><%= company.address %></td>
        <td><%= company.logo_large %></td>
        <td><%= company.logo_small %></td>
        <td><%= company.permalink %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Tax number:</strong>
  <%= @company.tax_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @company.password %>
</p>

<p>
  <strong>Contact person first name:</strong>
  <%= @company.contact_person_first_name %>
</p>

<p>
  <strong>Contact person last name:</strong>
  <%= @company.contact_person_last_name %>
</p>

<p>
  <strong>Contact person mobile number:</strong>
  <%= @company.contact_person_mobile_number %>
</p>

<p>
  <strong>Contact person email:</strong>
  <%= @company.contact_person_email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @company.website %>
</p>

<p>
  <strong>Office phone number:</strong>
  <%= @company.office_phone_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Mail verified:</strong>
  <%= @company.mail_verified %>
</p>

<p>
  <strong>Company verified:</strong>
  <%= @company.company_verified %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Logo large:</strong>
  <%= @company.logo_large %>
</p>

<p>
  <strong>Logo small:</strong>
  <%= @company.logo_small %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @company.permalink %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><%= image_tag("FolioLogo.png", size: "100x50", alt: "Edit Entry") %></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    
    <ul class="nav navbar-nav navbar-right" id="nav-bottom">
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Profile<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Folio4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/vacancies/_form.html.erb
<div class="panel-body">
<%= form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :position %>
    <%= f.text_field :position, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="checkbox">
    <%= f.label :from_home %>
    <%= f.check_box :from_home, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :salary %>
    <%= f.number_field :salary, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="checkbox">
    <%= f.label :show_salary %>
    <%= f.check_box :show_salary, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interview_address %>
    <%= f.text_field :interview_address, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="checkbox">
    <%= f.label :ongoing %>
    <%= f.check_box :ongoing, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/vacancies/edit.html.erb
<h1>Editing vacancy</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<h1>Listing vacancies</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Position</th>
      <th>Description</th>
      <th>Location</th>
      <th>From home</th>
      <th>Salary</th>
      <th>Interview address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.company_id %></td>
        <td><%= vacancy.position %></td>
        <td><%= vacancy.description %></td>
        <td><%= vacancy.location %></td>
        <td><%= vacancy.from_home %></td>
        <td><%= vacancy.salary %></td>
        <td><%= vacancy.show_salary %></td>
        <td><%= vacancy.interview_address %></td>
        <td><%= vacancy.ongoing %></td>
        <td><%= link_to 'Show', vacancy %></td>
        <% if @pin.user == current_user %>
          <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
          <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <div class="form-group">
    <%= link_to 'New Vacancy', new_vacancy_path, class: "btn btn-primary" %>
  </div>

app/views/vacancies/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New vacancy</h1>
  </div>

<%= render 'form' %>


<div class="panel-footer">
    <%= link_to 'Back', vacancies_path %>
  </div>
</div>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @vacancy.position %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vacancy.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @vacancy.location %>
</p>

<p>
  <strong>From home:</strong>
  <%= @vacancy.from_home %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @vacancy.salary %>
</p>

<p>
  <strong>Interview address:</strong>
  <%= @vacancy.interview_address %>
</p>

<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>